// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkGr9_24ZB1ifXAGVAJIs1990dQYpSgSw',
    appId: '1:471745302305:android:c990b131458efeab117860',
    messagingSenderId: '471745302305',
    projectId: 'try-auth-f5762',
    storageBucket: 'try-auth-f5762.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkrSjLp-8sYJ3fbWQH49GedP9L-9iEOKc',
    appId: '1:471745302305:ios:49c4fb21182c1e0e117860',
    messagingSenderId: '471745302305',
    projectId: 'try-auth-f5762',
    storageBucket: 'try-auth-f5762.firebasestorage.app',
    androidClientId: '471745302305-dn3dbl2ks77jqkajs9u2nivhrh4vrum0.apps.googleusercontent.com',
    iosClientId: '471745302305-n6okkh5s155equosej1tsiibbu0l09ua.apps.googleusercontent.com',
    iosBundleId: 'com.launchfast.app.launchfastFl',
  );
}
